# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(892, 627)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 481, 591))
        self.widget.setStyleSheet("QLabel{\n"
"\n"
"font-family: \'Poppins\', sans-serif;\n"
"}\n"
"QLineEdit {\n"
"\n"
"border : none;\n"
"border-bottom :2px solid rgb(7, 44, 96) ;\n"
"padding-bottom : 2px;\n"
"}\n"
"\n"
"QWidget {background-color:rgb(246, 245, 244);\n"
"border-top-left-radius:40px;\n"
"}\n"
"\n"
"QPushButton{\n"
"border:none;\n"
"border-radius:5px;\n"
"background-color:rgb(7, 44, 96);\n"
"color:white;\n"
"padding-top:2px ;\n"
"padding-bottom:2px;\n"
"height:30px;\n"
"font-family: \'Poppins\', sans-serif;\n"
"margin-left:5px;\n"
"marging right:5px;\n"
"}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.EmailTextField = QtWidgets.QLineEdit(self.widget)
        self.EmailTextField.setGeometry(QtCore.QRect(180, 280, 230, 29))
        self.EmailTextField.setObjectName("EmailTextField")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 250, 111, 27))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.LastNameTextField = QtWidgets.QLineEdit(self.widget)
        self.LastNameTextField.setGeometry(QtCore.QRect(180, 240, 230, 29))
        self.LastNameTextField.setObjectName("LastNameTextField")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(40, 290, 71, 27))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.FirstNameTextField = QtWidgets.QLineEdit(self.widget)
        self.FirstNameTextField.setGeometry(QtCore.QRect(180, 200, 230, 29))
        self.FirstNameTextField.setStyleSheet("")
        self.FirstNameTextField.setText("")
        self.FirstNameTextField.setPlaceholderText("")
        self.FirstNameTextField.setObjectName("FirstNameTextField")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(40, 210, 111, 27))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Indecator = QtWidgets.QLabel(self.widget)
        self.Indecator.setGeometry(QtCore.QRect(240, 80, 62, 17))
        self.Indecator.setText("")
        self.Indecator.setObjectName("Indecator")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(230, 350, 181, 36))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SignUpButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SignUpButton.setObjectName("SignUpButton")
        self.horizontalLayout.addWidget(self.SignUpButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(500, 10, 371, 591))
        self.widget_2.setStyleSheet("background-color:rgb(7, 44, 96);\n"
"\n"
"border-bottom-right-radius:40px;")
        self.widget_2.setObjectName("widget_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Last Name :"))
        self.label_3.setText(_translate("MainWindow", "Email :"))
        self.label.setText(_translate("MainWindow", "First Name :"))
        self.SignUpButton.setText(_translate("MainWindow", "Sign Up"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
